# config file
key: REDSTONE_TORCH_ON
bonus_chest: true
tp_radius: 256
protect_blocks: true
require_spout: false
default_world: false
default_world_name: world
include_default_world: false
worlds:
  world: true
  world 2: false