# config file
debug: false
key: STICK
bonus_chest: true
tp_radius: 256
protect_blocks: true
require_spout: false
default_world: false
default_world_name: myridiculouslylongworldnameiscalledcuthbert
include_default_world: false
platform: false
chameleon: true
sfx: true
give_key: false
the_end: false
nether: false
use_worldguard: true
respect_worldguard: true
respect_towny: true
respect_worldborder: true
land_on_water: true
timeout: 5
timeout_height: 135
name_tardis: false
border_radius: 64
create_worlds: true
rooms:
  PASSAGE: 250
  ARBORETUM: 500
  BEDROOM: 500
  KITCHEN: 500
  LIBRARY: 500
  POOL: 500
  VAULT: 500
#artron energy
player: 2
random: 25
travel: 50
comehere: 200
hide: 400
recharge_distance: 10
lightning_recharge: 100
creeper_recharge: 50
