# config file
key: STICK
bonus_chest: true
tp_radius: 256
max_distance: -1
border: square
protect_blocks: true
require_spout: false
default_world: false
default_world_name: world
include_default_world: false
platform: false
chameleon: true
sfx: true