# config file
debug: false
key: STICK
bonus_chest: true
tp_radius: 256
protect_blocks: true
require_spout: false
default_world: false
default_world_name: myridiculouslylongworldnameiscalledcuthbert
include_default_world: false
platform: false
chameleon: true
sfx: true
give_key: false
the_end: false
nether: false
use_worldguard: true
respect_worldguard: true
respect_towny: true
respect_worldborder: true
land_on_water: true
timeout: 5
timeout_height: 135
name_tardis: false
border_radius: 64
create_worlds: true
rooms:
  PASSAGE: 32
  ARBORETUM: 64
  BEDROOM: 64
  KITCHEN: 64
  LIBRARY: 64
  POOL: 64
  VAULT: 64
recharge_distance: 10
lightning_recharge: 100
creeper_recharge: 50