author: eccentric_nz
description: A plugin for all Doctor Who fans - create and use a TARDIS! Teleport to random destinations, fight randomly spawning monsters, bonus chests - it's bigger on the inside!
main: me.eccentric_nz.plugins.TARDIS.TARDIS
name: TARDIS
startup: postworld
softdepend: [Multiverse-Core,WorldGuard]
dev-url: http://de.bukkit.org/server-mods/TARDIS/
url: http://www.thenosefairy.co.nz/
version: '1.7.6'
permissions:
  tardis.admin:
    description: Allow players access to the TARDIS admin commands.
    default: op
  tardis.delete:
    description: Allow players to delete any TARDIS.
    default: false
  tardis.skeletonkey:
    description: Allow players to enter any TARDIS.
    default: false
  tardis.*:
    description: Allow players to create & delete a TARDIS, and teleport to destinations.
    children:
      tardis.create: true
      tardis.timetravel: true
      tardis.list: true
      tardis.save: true
      tardis.enter: true
      tardis.find: true
      tardis.add: true
      tardis.help: true
      tardis.update: true
      tardis.rebuild: true
    default: op
  tardis.exile:
    description: Disallow players from travelling anywhere but to areas they have a permission node for.
    default: false
  tardis.create:
    description: Allow players to create a TARDIS.
    default: op
  tardis.delete:
    description: Allow players to delete a TARDIS.
    default: op
  tardis.timetravel:
    TARDIS: Allow players to teleport to random locations and saved destinations.
    default: op
  tardis.list:
    TARDIS: Allow players to list saved time travel destinations.
    default: op
  tardis.save:
    TARDIS: Allow players to save time travel destinations.
    default: op
  tardis.home:
    TARDIS: Allow players to save a time travel destination as their home.
    default: op
  tardis.enter:
    description: Allow players to enter a TARDIS.
    default: op
  tardis.find:
    description: Allow players to find their TARDIS.
    default: op
  tardis.add:
    description: Allow players to add/remove companions to their TARDIS.
    default: op
  tardis.help:
    description: Allow players to view TARDIS help pages.
    default: true
  tardis.update:
    description: Allow players to modify the TARDIS interior.
    default: true
  tardis.rebuild:
    description: Allow players to rebuild the TARDIS.
    default: true
commands:
  tardis:
    description: Manipulate TARDISs (TARDII?) with various arguments (list, save, find, help, admin). Type /TARDIS help - to see more.
    list:
      description: List saved time travel locations.
      usage: /<command> list
      permission: tardis.list
      permission-message: You don't have the permission <permission> to use this command
    save:
      description: Save a time travel location.
      usage: /<command> save [slot number] [name]
      permission: tardis.save
      permission-message: You don't have the permission <permission> to use this command
    home:
      description: Save a time travel location as home.
      usage: /<command> home
      permission: tardis.home
      permission-message: You don't have the permission <permission> to use this command
    find:
      description: Shows you the location of your TARDIS.
      usage: /<command> find
      permission: tardis.find
      permission-message: You don't have the permission <permission> to use this command
    add:
      description: Add a companion that can travel with you in your TARDIS.
      usage: /<command> add [player name]
      permission: tardis.add
      permission-message: You don't have the permission <permission> to use this command
    remove:
      description: Remove a companion from your TARDIS.
      usage: /<command> remove [player name]
      permission: tardis.add
      permission-message: You don't have the permission <permission> to use this command
    update:
      description: Modify the interior of the TARDIS.
      usage: /<command> update [door|button|save-repeater|x-repeater|z-repeater|y-repeater]
      permission: tardis.update
      permission-message: You don't have the permission <permission> to use this command
    rebuild:
      description: Rebuild the TARDIS.
      usage: /<command> rebuild
      permission: tardis.rebuild
      permission-message: You don't have the permission <permission> to use this command
    chameleon:
      description: Toggle the TARDIS Chameleon Circuit on and off.
      usage: /<command> chameleon [on|off|add]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    sfx:
      description: Toggle the TARDIS sound effects on and off.
      usage: /<command> sfx [on|off]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    namekey:
      description: Rename the TARDIS key Item.
      usage: Hold the key in your hand, then type /<command> namekey [new name]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    travel:
      description: TRavel to destinations in various ways.
      usage: |
        /<command> travel [player] or /<command> travel [world x y z] or /<command> travel area [name]
        Example: /<command> travel eccentric_nz - travel to a players location
        Example: /<command> travel New_new_earth -117 64 273 - travel to co-ordinates in a specific world
        Example: /<command> travel New_new_earth -117 64 273 - travel to co-ordinates in a specific world
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    admin:
      description: Set TARDIS configuration options.
      usage: /<command> admin [config option] [value]
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    reload:
      description: Reloads the TARDIS configuration.
      usage: /<command> reload
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    help:
      description: View TARDIS help pages.
      usage: /<command> help [command]