author: eccentric_nz
description: A plugin for all Doctor Who fans - create and use a TARDIS! Teleport to random destinations, fight randomly spawning monsters, bonus chests - it's bigger on the inside!
main: me.eccentric_nz.plugins.TARDIS.TARDIS
name: TARDIS
startup: postworld
softdepend: [Multiverse-Core]
dev-url: http://dev.bukkit.org/server-mods/TARDIS/
url: http://www.thenosefairy.co.nz/
version: '1.4.3'
permissions:
  TARDIS.admin:
    description: Allow players access to the TARDIS admin commands.
    default: op
  TARDIS.delete:
    description: Allow players to delete any TARDIS.
    default: false
  TARDIS.*:
    description: Allow players to create & delete a TARDIS, and teleport to destinations.
    children:
      TARDIS.create: true
      TARDIS.delete: true
      TARDIS.timetravel: true
      TARDIS.list: true
      TARDIS.save: true
      TARDIS.enter: true
      TARDIS.find: true
      TARDIS.add: true
      TARDIS.help: true
      TARDIS.update: true
      TARDIS.rebuild: true
    default: op
  TARDIS.create:
    description: Allow players to create a TARDIS.
    default: op
  TARDIS.delete:
    description: Allow players to delete a TARDIS.
    default: op
  TARDIS.timetravel:
    TARDIS: Allow players to teleport to random locations and saved destinations.
    default: op
  TARDIS.list:
    TARDIS: Allow players to list saved time travel destinations.
    default: op
  TARDIS.save:
    TARDIS: Allow players to save time travel destinations.
    default: op
  TARDIS.home:
    TARDIS: Allow players to save a time travel destination as their home.
    default: op
  TARDIS.enter:
    description: Allow players to enter a TARDIS.
    default: op
  TARDIS.find:
    description: Allow players to find their TARDIS.
    default: op
  TARDIS.add:
    description: Allow players to add/remove companions to their TARDIS.
    default: op
  TARDIS.help:
    description: Allow players to view TARDIS help pages.
    default: true
  TARDIS.update:
    description: Allow players to modify the TARDIS interior.
    default: true
  TARDIS.rebuild:
    description: Allow players to rebuild the TARDIS.
    default: true
commands:
  tardis:
    description: Manipulate TARDISs (TARDII?) with various arguments (list, save, find, help, admin). Type /TARDIS help - to see more.
    list:
      description: List saved time travel locations.
      usage: /<command> list
      permission: TARDIS.list
      permission-message: You don't have the permission <permission> to use this command
    save:
      description: Save a time travel location.
      usage: /<command> save [slot number] [name]
      permission: TARDIS.save
      permission-message: You don't have the permission <permission> to use this command
    home:
      description: Save a time travel location as home.
      usage: /<command> home
      permission: TARDIS.home
      permission-message: You don't have the permission <permission> to use this command
    find:
      description: Shows you the location of your TARDIS.
      usage: /<command> find
      permission: TARDIS.find
      permission-message: You don't have the permission <permission> to use this command
    add:
      description: Add a companion that can travel with you in your TARDIS.
      usage: /<command> add [player name]
      permission: TARDIS.add
      permission-message: You don't have the permission <permission> to use this command
    remove:
      description: Remove a companion from your TARDIS.
      usage: /<command> remove [player name]
      permission: TARDIS.add
      permission-message: You don't have the permission <permission> to use this command
    update:
      description: Modify the interior of the TARDIS.
      usage: /<command> update [door|button|save-repeater|x-repeater|z-repeater|y-repeater]
      permission: TARDIS.update
      permission-message: You don't have the permission <permission> to use this command
    rebuild:
      description: Rebuild the TARDIS.
      usage: /<command> rebuild
      permission: TARDIS.rebuild
      permission-message: You don't have the permission <permission> to use this command
    travel:
      description: Modify the interior of the TARDIS.
      usage: |
        /<command> travel [player] or /<command> travel world x y z
        Example: /<command> travel eccentric_nz - travel to a players location
        Example: /<command> travel New_new_earth -117 64 273 - travel to co-ordinates in a specific world
      permission: TARDIS.timetravel
      permission-message: You don't have the permission <permission> to use this command
    admin:
      description: Set TARDIS configuration options.
      usage: /<command> admin [config option] [value]
      permission: TARDIS.admin
      permission-message: You don't have the permission <permission> to use this command
    reload:
      description: Reloads the TARDIS configuration.
      usage: /<command> reload
      permission: TARDIS.admin
      permission-message: You don't have the permission <permission> to use this command
    help:
      description: View TARDIS help pages.
      usage: /<command> help [command]